import logo from "../img/svg/logo.svg";
import wallpaper from '../img/wallpaper/wallpaper.jpg'
import avatarOne from '../img/wallpaper/image-1.jpg'
import avatarTwo from '../img/wallpaper/image-2.jpg'
import avatarThree from '../img/wallpaper/image-3.jpg'
import myAvatar from '../img/wallpaper/my-avatar.jpg'
export { logo }
export { wallpaper };
export { avatarOne };
export { avatarTwo };
export { avatarThree };
export { myAvatar };
